compare the system llvm against "big-merge" and "pgo"
fedora-llvm-team/llvm-snapshots pull request #672
Opened 2024-08-26 17:24 UTC by kwk

2024-08-26 19:32 UTC, kwk commented
# big-merge vs pgo

According to the llvm-test-suite the execution time of PGOed LLVM is 5,9% faster but 12% slower compile time and even worse 24% slower link time. This is for 20240825. I wonder how the comparison looks against the system compiler and if the results are really that bad every time.

```
Program                                       exec_time              compile_time              link_time             
                                              big-merge pgo    diff  big-merge    pgo    diff  big-merge pgo    diff 
SingleSource/UnitTests/testcase-Value-1                   0.00  inf%                0.02  inf%             0.02  inf%
Bitcode/Be...ral_grid/halide_bilateral_grid              15.93  inf%                0.00                   0.10  inf%
SingleSource/UnitTests/testcase-Expr-1                    0.00  inf%                0.02  inf%             0.02  inf%
SingleSour...tTests/testcase-CGExprConstant               0.00  inf%                0.02  inf%             0.02  inf%
SingleSour...nitTests/ms_struct_pack_layout               0.00  inf%                0.01  inf%             0.01  inf%
SingleSour...tTests/ms_struct_pack_layout-1               0.00  inf%                0.01  inf%             0.03  inf%
SingleSour...UnitTests/ms_struct-bitfield-1               0.00  inf%                0.01  inf%             0.02  inf%
SingleSour...Tests/member-function-pointers               0.00  inf%                0.02  inf%             0.06  inf%
SingleSour...ce/UnitTests/matrix-types-spec               0.00  inf%               13.72  inf%             0.05  inf%
SingleSource/UnitTests/initp1                             0.00  inf%                0.04  inf%             0.06  inf%
SingleSour...nitTests/2006-12-01-float_varg               0.00  inf%                0.02  inf%             0.02  inf%
SingleSour...Tests/2006-12-11-LoadConstants               0.00  inf%                0.07  inf%             0.02  inf%
SingleSour.../UnitTests/2008-04-20-LoopBug2               0.00  inf%                0.02  inf%             0.02  inf%
SingleSour...tTests/2008-07-13-InlineSetjmp               0.00  inf%                0.03  inf%             0.02  inf%
SingleSour...9-04-16-BitfieldInitialization               0.00  inf%                0.02  inf%             0.02  inf%
                           Geomean difference                  -5.9%                     12.0%                  24.3%
       exec_time                            compile_time                           link_time                          
l/r    big-merge           pgo         diff    big-merge          pgo        diff  big-merge          pgo         diff
count  40.000000  3.286000e+03  2450.000000  40.000000    2440.000000  446.000000  40.000000  2440.000000  2440.000000
mean   0.369140   1.512689e+03  inf          0.001442     0.205362     inf         0.074233   0.031629     inf        
std    1.868719   3.203588e+04 NaN           0.009123     1.697427    NaN          0.009413   0.025592    NaN         
min    0.003700   0.000000e+00 -0.577922     0.000000     0.000000     0.119584    0.059200   0.009700    -0.217391   
25%    0.006375   0.000000e+00 NaN           0.000000     0.000000    NaN          0.066775   0.016900    NaN         
50%    0.007300   8.000000e-04 NaN           0.000000     0.000000    NaN          0.073850   0.019500    NaN         
75%    0.008200   2.742774e+00 NaN           0.000000     0.000000    NaN          0.079550   0.025600    NaN         
max    11.552100  1.185607e+06  inf          0.057700     56.370900    inf         0.101200   0.174000     inf
```

2024-09-09 19:28 UTC, kwk commented
Experiments are done in an f41 container on x86_64 this time and the PGO profile generation was done using the llvm-test-suite instead of hello-world.

# big-merge vs pgo

```
Tests: 3307
Metric: exec_time,compile_time,link_time

Program                                       exec_time                compile_time               link_time              
                                              big-merge pgo    diff    big-merge    pgo    diff   big-merge pgo    diff  
Regression...ecute/GCC-C-execute-20060110-2     0.00      0.00    inf%   0.00         0.00          0.02      0.02  14.5%
Regression...ecute/GCC-C-execute-20070212-1     0.00      0.00    inf%   0.00         0.00          0.02      0.02  -3.0%
Regression...ecute/GCC-C-execute-20061101-2     0.00      0.00    inf%   0.00         0.00          0.02      0.02  -6.0%
Regression...ecute/GCC-C-execute-20050316-3     0.00      0.00    inf%   0.00         0.00          0.02      0.02  -4.2%
Regression...ecute/GCC-C-execute-20060110-1     0.00      0.00    inf%   0.00         0.00          0.03      0.02 -12.1%
Regression...execute/GCC-C-execute-920711-1     0.00      0.00    inf%   0.00         0.00          0.02      0.02   7.0%
Regression...execute/GCC-C-execute-920726-1     0.00      0.00    inf%   0.00         0.00          0.03      0.02 -34.3%
Regression...execute/GCC-C-execute-921029-1     0.00      0.00    inf%   0.00         0.00          0.03      0.02 -32.1%
Regression...execute/GCC-C-execute-921112-1     0.00      0.00    inf%   0.00         0.00          0.02      0.02   2.7%
Regression...execute/GCC-C-execute-921113-1     0.00      0.00    inf%   0.00         0.00          0.03      0.02 -24.1%
UnitTests/2020-01-06-coverage-007               0.00      0.00    inf%   0.02         0.02 -12.5%   0.02      0.02  -7.1%
UnitTests/2020-01-06-coverage-008               0.00      0.00    inf%   0.02         0.02 -24.3%   0.02      0.03  56.6%
Regression...execute/GCC-C-execute-921117-1     0.00      0.00    inf%   0.00         0.00          0.02      0.02 -11.7%
Regression...execute/GCC-C-execute-920829-1     0.00      0.00    inf%   0.00         0.00          0.02      0.02  14.9%
Regression...execute/GCC-C-execute-920908-1     0.00      0.00    inf%   0.00         0.00          0.02      0.02   7.8%
                           Geomean difference                  -100.0%                      -3.5%                   -8.4%
          exec_time                            compile_time                             link_time                          
l/r       big-merge           pgo         diff    big-merge          pgo        diff    big-merge          pgo         diff
count  3.286000e+03  3.286000e+03  2834.000000  2440.000000  2440.000000  446.000000  2440.000000  2440.000000  2440.000000
mean   1.511797e+03  1.512998e+03  inf          0.211009     0.206813    -0.022002    0.052811     0.049112    -0.052499   
std    3.205980e+04  3.208751e+04 NaN           1.764539     1.701700     0.158948    0.060011     0.057628     0.249021   
min    0.000000e+00  0.000000e+00 -1.000000     0.000000     0.000000    -0.504132    0.008900     0.010500    -0.704735   
25%    0.000000e+00  0.000000e+00 -0.080478     0.000000     0.000000    -0.104550    0.018900     0.017700    -0.226248   
50%    9.000000e-04  8.000000e-04  0.000000     0.000000     0.000000    -0.012053    0.022700     0.020900    -0.075171   
75%    2.726378e+00  2.701116e+00  0.142857     0.000000     0.000000     0.059316    0.041350     0.033300     0.089655   
max    1.207388e+06  1.203894e+06  inf          60.357200    56.157900    0.718750    0.265800     0.283400     1.683544
```

# System vs PGO

```
Tests: 3307
Metric: exec_time,compile_time,link_time

Program                                       exec_time                compile_time              link_time              
                                              18.1.8    pgo    diff    18.1.8       pgo    diff  18.1.8    pgo    diff  
UnitTests/2007-01-04-KNR-Args                   0.00      0.00    inf%   0.01         0.02 17.9%   0.02      0.02  17.8%
UnitTests/SignlessTypes/ccc                     0.00      0.00    inf%   0.02         0.02  0.9%   0.02      0.03  61.8%
UnitTests/Vector/Vector-sumarray-dbl            0.00      0.00    inf%   0.00         0.00         0.02      0.02   1.0%
UnitTests/Vector/Vector-sumarray                0.00      0.00    inf%   0.00         0.00         0.03      0.02 -17.9%
UnitTests/conditional-gnu-ext-cxx               0.00      0.00    inf%   0.01         0.02 18.0%   0.12      0.13   7.8%
Regression.../execute/GCC-C-execute-pr43385     0.00      0.00    inf%   0.00         0.00         0.02      0.02  -0.4%
Regression.../execute/GCC-C-execute-pr43560     0.00      0.00    inf%   0.00         0.00         0.02      0.02  17.3%
Regression...xecute/GCC-C-execute-pr42269-2     0.00      0.00    inf%   0.00         0.00         0.02      0.02  -5.6%
Regression.../execute/GCC-C-execute-pr42544     0.00      0.00    inf%   0.00         0.00         0.03      0.02 -40.7%
Regression.../execute/GCC-C-execute-pr42721     0.00      0.00    inf%   0.00         0.00         0.02      0.02   5.3%
Regression...ieee/GCC-C-execute-ieee-mzero2     0.00      0.00    inf%   0.00         0.00         0.02      0.02  -9.9%
Regression...e/GCC-C-execute-ieee-fp-cmp-4e     0.00      0.00    inf%   0.00         0.00         0.02      0.02 -25.3%
Regression...ee/GCC-C-execute-ieee-fp-cmp-5     0.00      0.00    inf%   0.00         0.00         0.02      0.02  11.3%
Regression...CC-C-execute-ieee-compare-fp-2     0.00      0.00    inf%   0.00         0.00         0.02      0.02  23.2%
Regression...e/GCC-C-execute-ieee-copysign2     0.00      0.00    inf%   0.00         0.00         0.03      0.02 -15.7%
                           Geomean difference                  -100.0%                      1.9%                  -10.6%
          exec_time                            compile_time                             link_time                          
l/r          18.1.8           pgo         diff       18.1.8          pgo        diff       18.1.8          pgo         diff
count  3.286000e+03  3.286000e+03  2851.000000  2440.000000  2440.000000  446.000000  2440.000000  2440.000000  2440.000000
mean   1.470319e+03  1.512998e+03  inf          0.205977     0.206813     0.030543    0.053702     0.049112    -0.072315   
std    3.127929e+04  3.208751e+04 NaN           1.730736     1.701700     0.150352    0.060762     0.057628     0.255466   
min    0.000000e+00  0.000000e+00 -1.000000     0.000000     0.000000    -0.768002    0.008900     0.010500    -0.739558   
25%    0.000000e+00  0.000000e+00 -0.125000     0.000000     0.000000    -0.046781    0.019600     0.017700    -0.250760   
50%    8.000000e-04  8.000000e-04  0.000000     0.000000     0.000000     0.024190    0.024100     0.020900    -0.101203   
75%    2.718482e+00  2.701116e+00  0.166667     0.000000     0.000000     0.098251    0.036325     0.033300     0.063237   
max    1.210631e+06  1.203894e+06  inf          58.378900    56.157900    0.682796    0.327400     0.283400     1.786517
```

# System vs big-merge

```
Tests: 3307
Metric: exec_time,compile_time,link_time

Program                                       exec_time                   compile_time                  link_time                 
                                              18.1.8    big-merge diff    18.1.8       big-merge diff   18.1.8    big-merge diff  
2007-03-02-VaCopy                               0.00      0.00       inf%   0.01         0.02     51.1%   0.02      0.02    -13.3%
2007-01-04-KNR-Args                             0.00      0.00       inf%   0.01         0.02     42.1%   0.02      0.02      6.3%
testcase-Value-1                                0.00      0.00       inf%   0.02         0.02     -3.7%   0.02      0.02     -3.4%
2006-12-01-float_varg                           0.00      0.00       inf%   0.02         0.01    -11. [...]

2025-03-17 13:42 UTC, kwk commented
<!--BEGIN REPORT-->
```mermaid
xychart-beta horizontal
    title "Compile time performance (20250317, x86_64, Fedora release 42 (Rawhide))"
    x-axis ["PGO vs. big-merge", "PGO vs. system", "big-merge vs. system"]
    y-axis "Geomean performance (in %)" -5.0 --> 26.8
    bar [21.8, 21.8, -0.0]
    line [21.8, 21.8, -0.0]
```

<details>
<summary>Compile time results for 20250317</summary>

<h2>big-merge (21.0.0pre20250317.g4fde8c341f9166) vs. PGO (21.0.0pre20250317.g4fde8c341f9166)</h2>

```
Tests: 7
Metric: compile_time

Program                                       compile_time                    
                                              big-merge    pgo-20250317 diff  
sqlite3/sqlite3                                 9.62         7.84       -18.5%
consumer-typeset/consumer-typeset               7.84         6.28       -19.9%
mafft/pairlocalalign                            8.35         6.61       -20.9%
SPASS/SPASS                                    11.50         9.04       -21.4%
tramp3d-v4/tramp3d-v4                          21.41        16.65       -22.2%
Bullet/bullet                                  26.30        19.82       -24.7%
kimwitu++/kc                                   11.35         8.50       -25.1%
                           Geomean difference                           -21.8%
      compile_time                       
l/r      big-merge pgo-20250317      diff
count  7.000000     7.000000     7.000000
mean   13.767286    10.677571   -0.217976
std    7.167952     5.332880     0.024165
min    7.837000     6.279700    -0.251000
25%    8.985450     7.224800    -0.234383
50%    11.345800    8.498000    -0.213757
75%    16.456900    12.848150   -0.203828
max    26.303500    19.819400   -0.184657
```

<h2>System (20.1.0) vs. big-merge (21.0.0pre20250317.g4fde8c341f9166)</h2>

```
Tests: 7
Metric: compile_time

Program                                       compile_time                         
                                              20.1.0       big-merge-20250317 diff 
mafft/pairlocalalign                            8.05         8.35              3.7%
tramp3d-v4/tramp3d-v4                          21.15        21.41              1.2%
kimwitu++/kc                                   11.24        11.35              1.0%
Bullet/bullet                                  26.20        26.30              0.4%
consumer-typeset/consumer-typeset               7.89         7.84             -0.7%
SPASS/SPASS                                    11.74        11.50             -2.0%
sqlite3/sqlite3                                 9.93         9.62             -3.1%
                           Geomean difference                                  0.0%
      compile_time                             
l/r         20.1.0 big-merge-20250317      diff
count  7.000000     7.000000           7.000000
mean   13.743086    13.767286          0.000689
std    7.090206     7.167952           0.022432
min    7.892400     7.837000          -0.030910
25%    8.990350     8.985450          -0.013483
50%    11.236300    11.345800          0.003782
75%    16.443900    16.456900          0.011021
max    26.204400    26.303500          0.036872
```

<h2>System (20.1.0) vs. PGO (21.0.0pre20250317.g4fde8c341f9166)</h2>

```
Tests: 7
Metric: compile_time

Program                                       compile_time                    
                                              20.1.0       pgo-20250317 diff  
mafft/pairlocalalign                            8.05         6.61       -18.0%
consumer-typeset/consumer-typeset               7.89         6.28       -20.4%
sqlite3/sqlite3                                 9.93         7.84       -21.0%
tramp3d-v4/tramp3d-v4                          21.15        16.65       -21.3%
SPASS/SPASS                                    11.74         9.04       -22.9%
Bullet/bullet                                  26.20        19.82       -24.4%
kimwitu++/kc                                   11.24         8.50       -24.4%
                           Geomean difference                           -21.8%
      compile_time                       
l/r         20.1.0 pgo-20250317      diff
count  7.000000     7.000000     7.000000
mean   13.743086    10.677571   -0.217638
std    7.090206     5.332880     0.023062
min    7.892400     6.279700    -0.243701
25%    8.990350     7.224800    -0.236550
50%    11.236300    8.498000    -0.212691
75%    16.443900    12.848150   -0.207098
max    26.204400    19.819400   -0.179777
```
</details>
<!--END REPORT-->

2025-03-17 14:07 UTC, tuliom requested changes
I have a few questions open and I'm suggesting a few cosmetic/comment changes.

2025-03-17 14:18 UTC, kwk commented on scripts/perf/Containerfile
> +         \
This is a left-over from the removal of the `perf` package and upon glancing at the PR I knew you would find it ;). Fixed in c5d4099.

2025-03-17 14:24 UTC, kwk commented on scripts/perf/Containerfile
> +RUN dnf install -y llvm-test-suite
Yes, this can be done. During development I mostly add layers in Containerfiles because of exactly this reason: Once I have all base-packages I move on and experiment with the new stuff. But now that I've settled to a particular list of packages and repos, this can be done in one step. See 73c7895.

2025-03-17 15:14 UTC, kwk commented on scripts/perf/entrypoint.sh
> +    ninja -j1
I've addressed this here: 7110a77

2025-03-17 15:24 UTC, tuliom commented on scripts/perf/README.md
> +This container setup allows you to compare the system llvm against "big-merge" and "pgo" for the current date.
Will the final commit use the description from the PR as the commit message?

2025-03-17 16:00 UTC, merged